


name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 # aalimsee is testing out GitHub Actions 🚀

# This will run every time we create push a commit.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on: [push]

jobs:
  # Get the current step to run the job
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." # 🎉 The job was automatically triggered by a "push" event.
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!" # 🐧 This job is now running on a "Linux" server hosted by GitHub!
      - run: echo "🔎 The name of your branch is ${{ github.ref }}" # The name of your branch is "refs/heads/main"
      
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner." # 💡 The "aalimsee/3.1-gh-basic-workflow" repository has been cloned to the runner.
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - run: echo "🍏 This job's status is ${{ job.status }}." # 🍏 This job's status is "success".